# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2529bcc097dc726defc3f4cc8d3fd619253fe1b36b8214b2356647507f62a883b63ec346fa6a9769de432f181e0a7fc9de7678ef2bf1446d2bc1ec0d4a075351

test:
  secret_key_base: 7c4aaa3b5c93288ca248816fdf1e7c45c1b50fc02b4d9490eac9a8ed74da7ecf55087716cf029df1d1321bfdafcbab6c1390c4b60f863eadf7ea1a369c3f14cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
